Models/Part.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PI_Project.Models
{
    public class Part
    {
        public int Id { get; set; }

        [StringLength(20, MinimumLength = 2)]
        [Required]
        [Display(Name = "Part name")]
        public String Part_name { get; set; }
        [Range(1, 100)]
        [Required]
        public uint Quantity { get; set; }

        [Display(Name = "Part description")]
        public String Part_desc { get; set; }
        [RegularExpression(@"^[A-Z]+[a-zA-Z0-9""'\s-]*$")]
        [StringLength(3)]
        [Required]
        [Display(Name = "Part location")]
        public String Part_loc { get; set; }
    }
}

Controllers/PartsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PI_Project.Data;
using PI_Project.Models;

namespace PI_Project.Controllers
{
    public class PartsController : Controller
    {
        private readonly PI_ProjectContext _context;



        public PartsController(PI_ProjectContext context)
        {
            _context = context;
        }



        [HttpPost]
        public string Index(string searchString, bool notUsed)
        {
            return "From [HttpPost]Index: filter on " + searchString;
        }

        // GET: Parts
        public async Task<IActionResult> Index(string partLocation, string searchString)
        {
            //System.Diagnostics.Debug.WriteLine("search id is: " + searchString);

            IQueryable<string> locationQuery = from m in _context.Part
                                               orderby m.Part_loc
                                               select m.Part_loc;

            var parts = from m in _context.Part select m;

            if (!string.IsNullOrEmpty(searchString))
            {
                parts = parts.Where(s => s.Part_name.Contains(searchString));
            }

            if (!string.IsNullOrEmpty(partLocation))
            {
                parts = parts.Where(x => x.Part_loc == partLocation);
            }

            var partLocVM = new PartLocationViewModel
            {
                Locations = new SelectList(await locationQuery.Distinct().ToListAsync()),
                Parts = await parts.ToListAsync()
            };

            return View(partLocVM);
            //@model IEnumerable<PI_Project.Models.Part>
        }

        // GET: Parts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var part = await _context.Part
                .FirstOrDefaultAsync(m => m.Id == id);
            if (part == null)
            {
                return NotFound();
            }

            return View(part);
        }

        // GET: Parts/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Parts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Part_name,Quantity,Part_desc,Part_loc")] Part part)
        {
            if (ModelState.IsValid)
            {
                _context.Add(part);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(part);
        }

        // GET: Parts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var part = await _context.Part.FindAsync(id);
            if (part == null)
            {
                return NotFound();
            }
            return View(part);
        }

        // POST: Parts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Part_name,Quantity,Part_desc,Part_loc")] Part part)
        {
            if (id != part.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(part);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PartExists(part.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(part);
        }

        // GET: Parts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var part = await _context.Part
                .FirstOrDefaultAsync(m => m.Id == id);
            if (part == null)
            {
                return NotFound();
            }

            return View(part);
        }

        // POST: Parts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var part = await _context.Part.FindAsync(id);
            _context.Part.Remove(part);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PartExists(int id)
        {
            return _context.Part.Any(e => e.Id == id);
        }
    }
}

Views/Parts/Create.cshtml
@model PI_Project.Models.Part

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>
<!--moga da vzema dannite ot login kakto se vzemat dannite ot create formata kym servera-->
<h4>Part</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Part_name" class="control-label"></label>
                <input asp-for="Part_name" class="form-control" />
                <span asp-validation-for="Part_name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Quantity" class="control-label"></label>
                <input asp-for="Quantity" class="form-control" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Part_desc" class="control-label"></label>
                <input asp-for="Part_desc" class="form-control" />
                <span asp-validation-for="Part_desc" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Part_loc" class="control-label"></label>
                <input asp-for="Part_loc" class="form-control" />
                <span asp-validation-for="Part_loc" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Parts/Delete.cshtml
@model PI_Project.Models.Part

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Part</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Part_name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Part_name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Quantity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Part_desc)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Part_desc)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Part_loc)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Part_loc)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Parts/Details.cshtml
@model PI_Project.Models.Part

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Part</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Part_name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Part_name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Quantity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Part_desc)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Part_desc)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Part_loc)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Part_loc)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Parts/Edit.cshtml
@model PI_Project.Models.Part

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Part</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Part_name" class="control-label"></label>
                <input asp-for="Part_name" class="form-control" />
                <span asp-validation-for="Part_name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Quantity" class="control-label"></label>
                <input asp-for="Quantity" class="form-control" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Part_desc" class="control-label"></label>
                <input asp-for="Part_desc" class="form-control" />
                <span asp-validation-for="Part_desc" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Part_loc" class="control-label"></label>
                <input asp-for="Part_loc" class="form-control" />
                <span asp-validation-for="Part_loc" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Parts/Index.cshtml
@model PI_Project.Models.PartLocationViewModel
@{
    ViewData["Title"] = "List of available spare parts";
}

<h1>List of available spare parts</h1>

<p style="border-bottom: none;">
    <a asp-action="Create"><button class="btn btn-primary">Create New</button></a>
</p>

<form asp-controller="Parts" asp-action="Index" method="get">
    <p>
        Part location:
        <select asp-for="PartLocation" asp-items="Model.Locations">
            <option value="">All</option>
        </select>

        Part name: <input type="text" asp-for="SearchString"/>
        <input type="submit" value="Filter"/>
    </p>
</form>



<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Parts[0].Part_name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Parts[0].Quantity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Parts[0].Part_desc)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Parts[0].Part_loc)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Parts) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Part_name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Quantity)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Part_desc)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Part_loc)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>